### ISSUE TITLE
Make protoc-gen-swagger build on 1.11

### ISSUE THREAD

**Issue by sumabn** [grpc-ecosystem/grpc-gateway#1044]
Tried to run go get inside dockerfile
RUN go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger

and got this error.

src/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/genswagger/generator.go:71:9: undefined: strings.ReplaceAll
The command '/bin/sh -c go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger' returned a non-zero code: 2

**Comment by johanbrandhorst** [comment]
https://golang.org/pkg/strings/#ReplaceAll was added in go 1.12, which was only ~8 months ago, so we may want to support at least go 1.11. To fix this right now, you could try upgrading to go 1.12 or go 1.13, but I think we should make this work in 1.11.

**Comment by johanbrandhorst** [comment]
What can I do to help you contribute a fix for this?

**Comment by achew22** [comment]
To expand on @johanbrandhorst, I think we would be happy to accept a patch to make the code compatible with 1.11, but the current group of maintainers is not going to write that. We only support two versions back in golang, but will accept compatibility patches into head.

**Comment by sumabn** [comment]
upgraded go version to 1.13 in docker. Now docker build is going through.
